language: python
python:
  - 3.6

install:
  - pip install -r scripts/requirements.txt

script:
  # Run from scratch
  - rm -rf archive/*
  - rm -rf data/
  - cd scripts
  - make

after_success:
        - ./push.sh

deploy:
  skip_cleanup: true
  github_token: $GITHUB_UPDATE_TOKEN
  email: db.update.bot@gmail.com
  name: db-update-bot
  keep_history: true
  provider: script
  script: make
  on:
    all_branches: true
