language: python
python:
- 3.6
install:
- pip install -r scripts/requirements.txt
script:
- rm -rf archive/*
- rm -rf data/
- cd scripts
- make
after_success:
- "./push.sh"
deploy:
  skip_cleanup: true
  target-branch: master
  github-token: "$GITHUB_TOKEN"
  keep_history: true
  provider: script
  script: make
  on:
    all_branches: true
