language: python
python:
  - 3.6

install:
  - pip install -r scripts/requirements.txt

script:
  # Run from scratch
  - rm -rf archive/*
  - rm -rf data/
  - cd scripts
  - make

after_success:
        - ./push.sh

deploy:
  skip_cleanup: true
  provider: script
  script: make
  on:
    all_branches: true
